[package]
name = "kawauso-config"
description = "Configuration files for Kawauso applications"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
indoc = { workspace = true }

[lints]
workspace = true
