[package]
name = "kawauso-config"
description = "Configuration files for Kawauso applications"

version = "0.0.0"

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

documentation = "https://docs.rs/kawauso-config"
readme = "README.md"

categories = ["config"]
keywords = ["configuration", "serde", "toml"]

include = [
  "LICENSE-APACHE",
  "LICENSE-MIT",
  "README.md",
  "src/**/*.rs",
  "tests/*.rs",
]

[dependencies]
dirs = { workspace = true }
serde = { workspace = true }
serde_path_to_error = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
typed-fields = { workspace = true }

[dev-dependencies]
indoc = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
